### ISSUE TITLE
Installing SDK via Cocoapods on build server

### ISSUE THREAD

**Issue by mtbohm** [inner-active/InneractiveAdSDK-iOS#1]
Hi,

Our company is currently using this repository in our production code. One issue we have not resolved yet relates to our preferred installation method, Cocoapods. The way this has been set-up for InnerActiveAdSDK is problematic because this is a private repository that my colleagues have not been invited to, so they cannot run `pod install` successfully (they are denied access). Our CircleCI build server also fails to build for the same reason.

Is there any reason why this is a private repository and not a public one, and if so, how would you recommend we proceed?

**Comment by 2energycell** [comment]
@MycujooMats the distribution went public: https://cocoapods.org/pods/VAMP
