### ISSUE TITLE
App Store Connect upload fails when using Fyber 8.2.7.0

### ISSUE THREAD

**Issue by Calabash-Boy** [inner-active/InneractiveAdSDK-iOS#67]
MAX Plugin Version 6.4.3
Xcode 15.2
Device/Platform Info iOS
Current Behavior
Currently facing this problem when trying to upload a production build to Testflight.

> Invalid Bundle. The bundle XXX.app/Frameworks/IASDKCore.framework does not support the minimum OS Version specified in the Info.plist.

It is ok if I downgrade Fyber's SDK to 8.2.6

When I try to fix this, I find this: [https://forums.developer.apple.com/forums/thread/705297](url)
there is the reason: the binary is MinimumOSVersion 12.0, but info.plist is 11.0, can you fix this?

**Comment by 2energycell** [comment]
Hi, when you use Xcode 15.2, the min iOS version is 12.0. Our SDK per se supports iOS 11, but it will not under Xcode 15.2, since Xcode itself supports at the minimum the iOS 12.
Also you can override the info.plist settings and define iOS 12 as min supported version.
Also our next release which is 8.3.0 supports min iOS version 12.0.
Thanks.

**Comment by icywire** [comment]
@Calabash-Boy When you use 8.2.7 or 8.2.8 make sure **you don't have** IASDKCore.xcframework linked directly to application target in Xcode. If it's there, try to remove that manually.
<img width="867" alt="Zrzut ekranu 2024-04-25 o 21 29 24" src="https://github.com/inner-active/InneractiveAdSDK-iOS/assets/830641/b060280f-290d-432e-917e-d14ec1de99ab">

Other option - update DT Exchange dependency in AppLovin dependency manager in Unity. Changing versions in Podfile only (without updating Unity plugins) may cause integration issues.
<img width="955" alt="Zrzut ekranu 2024-04-25 o 21 33 28" src="https://github.com/inner-active/InneractiveAdSDK-iOS/assets/830641/7900eee3-8726-44dc-94f5-536a4ea05997">

**Comment by Calabash-Boy** [comment]
> Hi, when you use Xcode 15.2, the min iOS version is 12.0. Our SDK per se supports iOS 11, but it will not under Xcode 15.2, since Xcode itself supports at the minimum the iOS 12. Also you can override the info.plist settings and define iOS 12 as min supported version. Also our next release which is 8.3.0 supports min iOS version 12.0. Thanks.

I had tried to override the  info.plist settings, but it cause signature error about IASDKCore.framework.
![image](https://github.com/inner-active/InneractiveAdSDK-iOS/assets/21103813/3385f679-45ec-4a59-9a60-66fd9283b728)
Am i right?

**Comment by Calabash-Boy** [comment]
> @Calabash-Boy When you use 8.2.7 or 8.2.8 make sure **you don't have** IASDKCore.xcframework linked directly to application target in Xcode. If it's there, try to remove that manually. <img alt="Zrzut ekranu 2024-04-25 o 21 29 24" width="867" src="https://private-user-images.githubusercontent.com/830641/325747201-b060280f-290d-432e-917e-d14ec1de99ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTkxMTEsIm5iZiI6MTcxNDA5ODgxMSwicGF0aCI6Ii84MzA2NDEvMzI1NzQ3MjAxLWIwNjAyODBmLTI5MGQtNDMyZS05MTdlLWQxNGVjMWRlOTlhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMjMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjUzNGM5OTkyM2FiYTZkNGEwMjcwNTUyOGFjM2RkNzZmYmM3NWY1ZDIzMjJlNTY0NDE4OGE5MjBiNjg3YjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChQJfKdx7Ubxxzkl_Akkb14pwrXmR9VErLnkqmfq-5Q">
> 
> Other option - update DT Exchange dependency in AppLovin dependency manager in Unity. Changing versions in Podfile only (without updating Unity plugins) may cause integration issues. <img alt="Zrzut ekranu 2024-04-25 o 21 33 28" width="955" src="https://private-user-images.githubusercontent.com/830641/325747228-7900eee3-8726-44dc-94f5-536a4ea05997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTkxMTEsIm5iZiI6MTcxNDA5ODgxMSwicGF0aCI6Ii84MzA2NDEvMzI1NzQ3MjI4LTc5MDBlZWUzLTg3MjYtNDRkYy05NGY1LTUzNmE0ZWEwNTk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMjMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjRjOTFhMzY4ZjZmODA0ZTc4YThhZDM2YTY1NWVhNTQzNmUwZjkzZWM2MTQ4NjNkMWI0ODQ4OGI5MTRiMjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qn0NiSBAf4t1B_nLS9lyje5v1_J5jVIMjzKoRXcx4B4">

Yes, I don't have IASDKCore.xcframework linked directly to application target.
as @2energycell said, Fyber 8.3.0 will fix this.

**Comment by Calabash-Boy** [comment]
@2energycell I have one more question:
Xcode 15.2
Fyber 8.2.6 works well!
Fyber 8.2.7 upload fails?
Both in Xcode 15.2, why is that?

**Comment by icywire** [comment]
8.2.6 is dynamic framework, 8.2.7 is static framework.

This is Xcode issue, Apple is working on it, check this thread https://developer.apple.com/forums/thread/749554
For some developers downgrading Xcode to 15.1 or 15.0 helped.
