### ISSUE TITLE
Crash in SDK 8.3.4

### ISSUE THREAD

**Issue by jruston** [inner-active/InneractiveAdSDK-iOS#78]
I am seeing two similar looking types of crashes in the 8.3.4 SDK. I was previously using 8.3.2 and did not see these crashes. They look like the below:

Crashed: com.apple.root.background-qos
0  libdispatch.dylib              0x28e0 _os_object_retain + 68
1  MyApp          0xb0d31c specialized static Swift_Shim_Config_Fetch.disable() + 4386853660
2  MyApp          0xac42ec __44-[IAConfigurationManager updateGlobalConfig]_block_invoke + 4386554604
3  MyApp          0xaf03bc thunk for @escaping @callee_unowned @convention(block) (@unowned NSError?, @unowned NSString) -> () + 4386735036
4  MyApp          0xaf0214 closure #1 in DTXConfigManager.updateGlobalConfig(completion:) + 4386734612
5  MyApp          0xb26fa0 closure #1 in DTXConfigRepository.updateGlobalConfig(with:completion:) + 4386959264
6  MyApp          0xb25a00 specialized closure #2 in DTXRemoteFilesDataSource.downloadObject<A>(url:lastModified:timeout:completion:) + 4386953728
7  MyApp          0xaf450c closure #1 in DTXNetworkSession.urlSession(_:task:didCompleteWithError:) + 4386751756
8  MyApp          0x352a0 thunk for @escaping @callee_guaranteed @Sendable () -> () + 4375483040
9  libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
10 libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
11 libdispatch.dylib              0x15f60 _dispatch_root_queue_drain + 860
12 libdispatch.dylib              0x16590 _dispatch_worker_thread2 + 156
13 libsystem_pthread.dylib        0x4c40 _pthread_wqthread + 228
14 libsystem_pthread.dylib        0x1488 start_wqthread + 8

Crashed: com.Fyber.SDK.Marketplace.core.networking.client.result
0  libdispatch.dylib              0x28e0 _os_object_retain + 68
1  MyApp          0xb0d54c specialized static Swift_Shim_Config_Fetch.setFeaturesConfig(fetchTime:code:) + 4315387212
2  MyApp          0xb0b0e0 @objc static Swift_Shim_Config_Fetch.setFeaturesConfig(fetchTime:code:) + 4315377888
3  MyApp          0xae4908 -[FMPABTestingConfigManager networkingClient:succeededWithHTTPStatusCode:headers:data:] + 4315220232
4  MyApp          0xa09ac8 __59-[IANetworkingClient URLSession:task:didCompleteWithError:]_block_invoke + 4314323656
5  libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
7  libdispatch.dylib              0xb6d8 _dispatch_lane_serial_drain + 744
8  libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 380
9  libdispatch.dylib              0x17258 _dispatch_root_queue_drain_deferred_wlh + 288
10 libdispatch.dylib              0x16aa4 _dispatch_workloop_worker_thread + 540
11 libsystem_pthread.dylib        0x4c7c _pthread_wqthread + 288
12 libsystem_pthread.dylib        0x1488 start_wqthread + 8

**Comment by 2energycell** [comment]
Thanks @jruston for the report, this issue is already addressed and the fix is planned to be part of the next release.

**Comment by jruston** [comment]
@2energycell Do you have an estimate of when the next release will be available? This crash is one of the top crashes in my apps, so it would be nice to have it resolved.

**Comment by SergeyNesteruk** [comment]
> [@2energycell](https://github.com/2energycell) Do you have an estimate of when the next release will be available? This crash is one of the top crashes in my apps, so it would be nice to have it resolved.

+1 asking for an estimate @2energycell

**Comment by 2energycell** [comment]
@jruston @SergeyNesteruk the 8.3.5 has been released, it addresses the issue;
